examples: add SIO Output RTSP example (#35)
* Move examples to root path

* sh-services: services can depend on other services

* live555: enable port

* Add SIOOutput example

* README.md: Update Quick start

* examples: rename SIO_OUTPUT project
Signed-off-by: Pablo Rodriguez Quesada <prodriguez@sighthound.com>

* mcp: depends on rabbitmq

Signed-off-by: Pablo Rodriguez Quesada <prodriguez@sighthound.com>

* Restructure examples

* Add sio_output example

---------

Signed-off-by: Pablo Rodriguez Quesada <prodriguez@sighthound.com>

diff --git a/scripts/sh-services b/scripts/sh-services
--- a/scripts/sh-services
+++ b/scripts/sh-services
@@ -17,6 +17,26 @@ check_endpoint() {
   curl --output /dev/null --silent --head $@ "$1"
 }
 
+check_service_up() {
+    local service=$1
+    count=$(docker-compose -f "${service}/docker-compose.yml" ps | sed '1,2d' | grep -c "Up")
+    total=$(docker-compose -f "${service}/docker-compose.yml" ps | sed '1,2d' | grep -c "^")
+    if [ "$total" -eq "0" ]; then
+        echo "No ${service} containers are up"
+        return 1
+    elif [ "$count" -eq "$total" ]; then
+        echo "All ${service} containers are up"
+        echo "live555:"
+        docker-compose -f "${service}/docker-compose.yml" ps | sed '1,2d'
+        return 0
+    else
+        echo "Some ${service} containers are not up"
+        echo "live555:"
+        docker-compose -f "${service}/docker-compose.yml" ps | sed '1,2d'
+        return 1
+    fi
+}
+
 # Merge the services
 # First file has the highest priority
 function merge_env_files(){
@@ -75,7 +95,7 @@ function save_arch_info(){
 }
 
 function merge(){
-    service=$1
+    local service=$1
     touch "${service}/.env"
     env_files_to_merge="${service}/.env"
 
@@ -101,7 +121,7 @@ function merge(){
 }
 
 function edit(){
-    service=$1
+    local service=$1
     merge "${service}"
     echo "Editing ${service}"
     touch "${service}/conf/0001-edit.env"
@@ -123,7 +143,7 @@ function create_network(){
 }
 
 function depends(){
-    service=$1
+    local service=$1
     # Check if the folder contains the "depends" file
     if [ -f "${service}/depends" ]; then
         # Read the contents of the "depends" file
@@ -135,21 +155,24 @@ function depends(){
                 gateway_ip=$(awk '/32 host/ { print i } {i=$2}' /proc/net/fib_trie | head -n 1 | awk -F'.' '{$NF="1"}1' OFS='.')
                 endpoint=${endpoint/gateway_ip/$gateway_ip}
             fi
+            up=0
             # Loop for 15 seconds or until the endpoint is up
             for ((i=0; i<15; i++)); do
                 if check_endpoint "$endpoint"; then
                     # Endpoint is up, so print "service ready"
                     echo "Endpoint '$endpoint' is ready"
-                    return 0
+                    up=1
+                    break
                 else
                     echo "Waiting for endpoint: '$endpoint' to be up..."
                     sleep 3
                 fi
             done
-            # Endpoint was not up after 45 seconds, so stop the execution
-            echo "Error: endpoint '$endpoint' was not up after 45 seconds"
-            echo "Continuing execution."
-            return 0
+            if [ $up -eq 0 ]; then
+                # Endpoint was not up after 15 seconds, so stop the execution
+                echo "Error: endpoint '$endpoint' was not up after 15 seconds"
+                echo "Continuing execution."
+            fi
         done
 
         files=$(grep "file" "${service}"/depends | awk '{print $2}')
@@ -159,10 +182,33 @@ function depends(){
             if [ -f "$file" ]; then
                 # File is up, so print "service ready"
                 echo "File '$file' is available."
-                return 0
             else
                 echo "File is not available: '$file'. Stopping execution"
                 return 1
+            fi
+        done
+
+        enabled_services_up=$(grep "enabled_service_up" "${service}"/depends | awk '{print $2}')
+
+        # Loop through the services
+        for enabled_service in $enabled_services_up; do
+            if [ -f "${SERVICES_PATH}/${enabled_service}/disabled" ]; then
+                echo "Service '$enabled_service' is disabled. Skipping"
+            else
+                up=0
+                for ((i=0; i<5; i++)); do
+                    if ! check_service_up "${SERVICES_PATH}/${enabled_service}" ; then
+                        echo "Waiting for service: '$enabled_service' to be up..."
+                        sleep 3
+                    else
+                        up=1
+                        break
+                    fi
+                done
+                if [ $up -eq 0 ]; then
+                    echo "Error: service '$enabled_service' was not up after 15 seconds"
+                    echo "Continuing execution."
+                fi
             fi
         done
     fi
@@ -170,7 +216,7 @@ function depends(){
 }
 
 function up(){
-    service=$1
+    local service=$1
     # Check if disabled file exists
     if [ -f "${service}/disabled" ]; then
         echo "Skipping ${service} : disabled file found"
@@ -184,7 +230,7 @@ function up(){
 }
 
 function compose_up(){
-    service=$1
+    local service=$1
     if ! depends "${service}"; then
         echo "Skipping ${service} : depends failed"
         return
@@ -196,7 +242,7 @@ function compose_up(){
 }
 
 function down(){
-    service=$1
+    local service=$1
     echo "Stopping ${service}"
     cd "${service}" || exit 1
     ${DOCKER_COMPOSE} down
@@ -204,13 +250,13 @@ function down(){
 }
 
 function restart(){
-    service=$1
+    local service=$1
     down "${service}"
     up "${service}"
 }
 
 function enable(){
-    service=$1
+    local service=$1
     if [ -f "${service}/disabled" ]; then
         echo "Enabling ${service}."
         rm  "${service}/disabled"
@@ -220,7 +266,7 @@ function enable(){
 }
 
 function disable(){
-    service=$1
+    local service=$1
     if [ -f "${service}/disabled" ]; then
         echo "Skipping ${service} : disabled file found."
         return
@@ -234,9 +280,7 @@ function element_in_list(){
     element=$1
     shift
     list=( $@ )
-    echo "Checking if ${element} is in ${list[*]}"
     for e in "${list[@]}"; do
-        echo "Checking $e"
         if [ "$e" == "$element" ]; then
             return 0
         fi
